
utils::globalVariables(c("adduct_b", "isoab_b", "idx", "int_wo_spikes", "rt", "StartTime",
                         "EndTime", "int", "isoab", "FileName", "adduct", "main_adduct",
                         "peaks.PpP", "molecule", "i", "charge", "root", "..currentCols",
                         "values", ".N", ".SD", "parents", "ids", "resolution_list", "adducts",
                         "js", "Lost_b.A", "BM.div", "Molecule", "Adduct", ".GRP", "maIso",
                         "IDX", "rt_add_temp", "rt_end_b", "rt_b", "rt_start_b", "sample_id_ug",
                         "rt_start_ug", "rt_end_ug", "rt_ug", "mz_ug", "sample_id_b",
                         "peak_core_rt_range_start_b", "peak_core_rt_range_end_b", "mz_start_b", "mz_end_b", "rt_end_ug_temp",
                         "mz_start_b_temp", "mz_ug_temp", "mz_end_b_temp", "rt_ug_temp",
                         "main_peak", "peak_area_g", "sample_id_g", "peak_area_ug", "N_fid",
                         "molecule_b", "feature_id_g", "id_b_ug", "comp_id_b", "comp_id_ug",
                         "main_feature", "dpl", "area_b", "sample_name_b", "..join_vct",
                         "peak_area_b", "area_g", "Connected", "peak_height_b", "i.peak_area_b",
                         "i.peak_area_ug", "i.area_g", "diffH20PP_pp", "benchmark", "diffH20PP_ft",
                         "NPP_features", "missing_peaks_g", "Min.errors", "V1", "..iso_to_test",
                         "peak_status", "unres.s", "s", "e", "unres.e", "feature_id_b",
                         "min_mz_start", "max_mz_end", "min_rt_start", "max_rt_end", "mz_g",
                         "rt_g", "sample_name", "eic_mzmin", "eic_mzmax", "MinMz", "MaxMz",
                         "isoab_ol", "peaks.idx", "peaks.M0.grp", "Iso_count", "sample_group",
                         "Grp", "iso_id", "mz_ex", "feature_id", "ft_count", "iso_count2",
                         "rt_diff", "peaks.rt_raw", "user.rt", "min_rt_diff", "rt_raw_span",
                         "r_s_error", "sample_id", "b_samples", "RT.v", "Intensities.v", "rt_measure",
                         "val", "len", "user.rtmin", "user.rtmax", "fileIdx", "roi_id",
                         "scmin", "scmax", "mz", "mzmin", "mzmax", "..bestIso", "adduct_c",
                         "SumForm2_c", "value", "abundance", "formula", "m/z", "v", "l",
                         "height", "V.1", "vars", "id", "g_samples", "peak_area", "rt_start",
                         "rt_end", "peak_length", "isoab_b.x", "isoab_b.y", "ratio_diff",
                         "RT.v_b", "Intensities.v_b", "peaks.StartTime", "peaks.EndTime",
                         "start", "end", "start.ut", "end.ut", "peak_found", "nr", "..vct",
                         "colors", "i.peaks.area", "peaks.area", "i.peaks.height", "peaks.height",
                         "ExpectedArea", "ErrorRel_A", "ErrorAbs_A", "ExpectedHeight",
                         "ErrorRel_H", "ErrorAbs_H", "peaks.mz_accurate", "Precursor Name",
                         "min_ratio_diff", "StartTime.EIC", "EndTime.EIC", "Split_peak",
                         "present_in_found", "NPP_status", "peak_height", "i.sample_id",
                         "false_negative", "feature_id_b_temp", "false_negative_type",
                         "rt_diff_min", "keep_rt", "mz_diff_min", "peaks.mz_accuracy_ppm",
                         "keep_mz", "sample_id_b_temp", "sample_id_ug_temp", "peak_core_rt_range_start_b_temp",
                         "rt_start_ug_temp", "peak_core_rt_range_end_b_temp", "peak_area_ug_temp",
                         "peak_area_rounded_ug", "peak_area_g_temp", "sample_id_g_temp",
                         "i.peaks.rt_neighbors_b", "peaks.rt_neighbors_b", "i.peaks.mz_neighbors_b",
                         "peaks.mz_neighbors_b", "missing_peaks_ug", "valley_diff", "min_mz_start_temp",
                         "max_mz_end_temp", "min_rt_start_temp", "max_rt_end_temp", "M0_int",
                         "rtmin", "rtmax", "peaks.cor_w_main_add", "peaks.cor_w_M0", "area_ratio",
                         "mean_area_g.y", "mean_area_g.x", "first_found_area_temp", "int_smooth",
                         "sc.i", "mzlowerBD", "mzupperBD", "filename", "average_area",
                         "merge_key", "no_of_samples", "peak_area_ug.y", "peak_area_ug.x",
                         "f_nf_col", "..var", "var_r", "N", "n", "diffH20PP",
                         "grp_col", "data_type", "Pred_error", "RT_neighbors", "mz_neighbors",
                         "missing_peaks", "plot_group", "ord", "ErrorRel_A_b", "order_temp",
                         ".I", "area_diff", "..entrustedGrp", "Peptide", "NPP_peak", "Peptide Modified Sequence", ".",
                         ":=", "NPP_peak", "NPP_peak picking", "focus", "ug_samples", "i.sample_name_b", "mz_b",
                         "rt_start_b_temp", "rt_end_b_temp", "match_tables_with_alignment_recovery_info"))
